# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\mqtt\mqtt.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label_head = QtWidgets.QLabel(self.centralWidget)
        self.label_head.setGeometry(QtCore.QRect(50, 40, 231, 61))
        self.label_head.setObjectName("label_head")
        self.groupBox_control = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_control.setGeometry(QtCore.QRect(40, 110, 291, 231))
        self.groupBox_control.setObjectName("groupBox_control")
        self.lineEdit_ID = QtWidgets.QLineEdit(self.groupBox_control)
        self.lineEdit_ID.setGeometry(QtCore.QRect(80, 40, 81, 21))
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.label_ID = QtWidgets.QLabel(self.groupBox_control)
        self.label_ID.setGeometry(QtCore.QRect(20, 40, 51, 21))
        self.label_ID.setObjectName("label_ID")
        self.groupBox_voice_con = QtWidgets.QGroupBox(self.groupBox_control)
        self.groupBox_voice_con.setGeometry(QtCore.QRect(10, 80, 261, 61))
        self.groupBox_voice_con.setObjectName("groupBox_voice_con")
        self.pushButton_OnVoice = QtWidgets.QPushButton(self.groupBox_voice_con)
        self.pushButton_OnVoice.setGeometry(QtCore.QRect(30, 20, 81, 31))
        self.pushButton_OnVoice.setObjectName("pushButton_OnVoice")
        self.pushButton_OffVoice = QtWidgets.QPushButton(self.groupBox_voice_con)
        self.pushButton_OffVoice.setGeometry(QtCore.QRect(160, 20, 81, 31))
        self.pushButton_OffVoice.setObjectName("pushButton_OffVoice")
        self.groupBox_video_con = QtWidgets.QGroupBox(self.groupBox_control)
        self.groupBox_video_con.setGeometry(QtCore.QRect(10, 150, 261, 61))
        self.groupBox_video_con.setObjectName("groupBox_video_con")
        self.pushButton_OffVideo = QtWidgets.QPushButton(self.groupBox_video_con)
        self.pushButton_OffVideo.setGeometry(QtCore.QRect(160, 20, 81, 31))
        self.pushButton_OffVideo.setObjectName("pushButton_OffVideo")
        self.pushButton_OnVideo = QtWidgets.QPushButton(self.groupBox_video_con)
        self.pushButton_OnVideo.setGeometry(QtCore.QRect(30, 20, 81, 31))
        self.pushButton_OnVideo.setObjectName("pushButton_OnVideo")
        self.pushButton_connect = QtWidgets.QPushButton(self.groupBox_control)
        self.pushButton_connect.setGeometry(QtCore.QRect(180, 40, 75, 23))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.groupBox_subscribe = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_subscribe.setGeometry(QtCore.QRect(40, 360, 291, 191))
        self.groupBox_subscribe.setObjectName("groupBox_subscribe")
        self.groupBox_voice_sub = QtWidgets.QGroupBox(self.groupBox_subscribe)
        self.groupBox_voice_sub.setGeometry(QtCore.QRect(10, 30, 261, 61))
        self.groupBox_voice_sub.setObjectName("groupBox_voice_sub")
        self.pushButton_RecVoice = QtWidgets.QPushButton(self.groupBox_voice_sub)
        self.pushButton_RecVoice.setGeometry(QtCore.QRect(30, 20, 81, 31))
        self.pushButton_RecVoice.setObjectName("pushButton_RecVoice")
        self.pushButton_UnrecVoice = QtWidgets.QPushButton(self.groupBox_voice_sub)
        self.pushButton_UnrecVoice.setGeometry(QtCore.QRect(160, 20, 81, 31))
        self.pushButton_UnrecVoice.setObjectName("pushButton_UnrecVoice")
        self.groupBox_video_sub = QtWidgets.QGroupBox(self.groupBox_subscribe)
        self.groupBox_video_sub.setGeometry(QtCore.QRect(10, 110, 261, 61))
        self.groupBox_video_sub.setObjectName("groupBox_video_sub")
        self.pushButton_RecVideo = QtWidgets.QPushButton(self.groupBox_video_sub)
        self.pushButton_RecVideo.setGeometry(QtCore.QRect(30, 20, 81, 31))
        self.pushButton_RecVideo.setObjectName("pushButton_RecVideo")
        self.pushButton_UnrecVideo = QtWidgets.QPushButton(self.groupBox_video_sub)
        self.pushButton_UnrecVideo.setGeometry(QtCore.QRect(160, 20, 81, 31))
        self.pushButton_UnrecVideo.setObjectName("pushButton_UnrecVideo")
        self.groupBox_radio = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_radio.setGeometry(QtCore.QRect(370, 110, 401, 441))
        self.groupBox_radio.setObjectName("groupBox_radio")
        self.pushButton_add = QtWidgets.QPushButton(self.groupBox_radio)
        self.pushButton_add.setGeometry(QtCore.QRect(30, 30, 91, 31))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_del = QtWidgets.QPushButton(self.groupBox_radio)
        self.pushButton_del.setGeometry(QtCore.QRect(30, 90, 91, 31))
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_list = QtWidgets.QPushButton(self.groupBox_radio)
        self.pushButton_list.setGeometry(QtCore.QRect(30, 150, 91, 31))
        self.pushButton_list.setObjectName("pushButton_list")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_radio)
        self.textBrowser.setGeometry(QtCore.QRect(155, 30, 231, 391))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(300, 50, 91, 41))
        self.pushButton_exit.setObjectName("pushButton_exit")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.pushButton_exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_head.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">多媒体远程终端控制系统</span></p></body></html>"))
        self.groupBox_control.setTitle(_translate("MainWindow", "远程控制"))
        self.label_ID.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">用户ID：</span></p></body></html>"))
        self.groupBox_voice_con.setTitle(_translate("MainWindow", "语音控制"))
        self.pushButton_OnVoice.setText(_translate("MainWindow", "开启"))
        self.pushButton_OffVoice.setText(_translate("MainWindow", "关闭"))
        self.groupBox_video_con.setTitle(_translate("MainWindow", "视频控制"))
        self.pushButton_OffVideo.setText(_translate("MainWindow", "关闭"))
        self.pushButton_OnVideo.setText(_translate("MainWindow", "开启"))
        self.pushButton_connect.setText(_translate("MainWindow", "连接"))
        self.groupBox_subscribe.setTitle(_translate("MainWindow", "信息获取"))
        self.groupBox_voice_sub.setTitle(_translate("MainWindow", "语音获取"))
        self.pushButton_RecVoice.setText(_translate("MainWindow", "开启"))
        self.pushButton_UnrecVoice.setText(_translate("MainWindow", "关闭"))
        self.groupBox_video_sub.setTitle(_translate("MainWindow", "视频获取"))
        self.pushButton_RecVideo.setText(_translate("MainWindow", "开启"))
        self.pushButton_UnrecVideo.setText(_translate("MainWindow", "关闭"))
        self.groupBox_radio.setTitle(_translate("MainWindow", "管理"))
        self.pushButton_add.setText(_translate("MainWindow", "添加好友"))
        self.pushButton_del.setText(_translate("MainWindow", "删除好友"))
        self.pushButton_list.setText(_translate("MainWindow", "在线好友"))
        self.pushButton_exit.setText(_translate("MainWindow", "退出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

